### ISSUE TITLE
Cannot handle image with sizes other 640/320

### ISSUE THREAD

**Issue by RitiP** [GuoyaoShen/K-SapceColdDIffusion#1]
Hi,

Thank you for making your code available! I have observed that the provided code expects data to always be of the size of 320x320 or 640x320. Since the reconstruction network is UNET which is independent of the data size, I was wondering as to why such a restriction is placed on the network.
I have also attempted to execute the code on the fastMRI brain dataset, which has samples of varying sizes. The training fails when it encounters samples of sizes other than 320. Any insight provided on this would be great.

**Comment by GuoyaoShen** [comment]
Hi,

Indeed UNet is independent of the input data size, meaning that it can be applied to different image shapes as needed. We cropped all images into the size of 320x320 to ensure a fair comparison among all other models during our tests.

fastMRI dataset includes multiple sizes other than 640x320. A quick and easy way for this is to first get the fully-sampled reconstruction image and crop it into 320x320 (such that you don't loose any image details), then back calculate to the k-space and apply sampling masks. In this way, you can handle different shapes in a batch.
